#!bin/bash

if test $UPSTREAM_REPO ; then
   git clone -q $UPSTREAM_REPO ubot
else
   git clone -q https://github.com/TgCatUB/catuserbot ubot
fi

pip -q install --no-cache-dir -r ubot/requirements.txt

bash python -m ubot
